model:
  hidden_layers: [512, 512, 512, 512]
  activation: relu
  batch_norm: true
  dropout_p: 0.05
dataset:
  name: pb2007
  art_type: art_params
  sound_type: cepstrum
  datasplits_size: [80, 20, 0] # train/validation/test in percentage
  datasplit_seed: null
  batch_size: 8
  num_workers: 6
  shuffle_between_epochs: true
training:
  learning_rate: 0.0005
  max_epochs: 500
  patience: 25
