  model:
    inverse_model:
      num_layers: 2
      hidden_size: 64
      dropout_p: 0.17
      bidirectional: true
  synthesizer:
    name: mel_synth_20_ms
  vocoder:
    name: cp_hifigan_20_ms/g_00190000
#  feature_extractor:
#    name: facebook/wav2vec2-base-10k-voxpopuli
#    layer: 12
#    sampling_rate: 16000
  feature_extractor:
      name: mfcc
      n_mfcc: 13
      n_fft: 320
      hop_length: 160
      n_mels: 26
      add_delta: true
      sampling_rate: 16000
  dataset:
    name: pb2009
    sound_type: wav
    source_type: source
    datasplits_size: [64, 16, 20] # train/validation/test in percentage
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
    cut_silences: true
    max_len: 38400
  training:
    learning_rate: 0.0017
    discriminator_model_learning_rate: 0.002
    max_epochs: 500
    patience: 30
    jerk_loss_weight: 0
    discriminator_loss_weight: 0

