M0_10_mn:
  model:
    direct_model:
      hidden_layers: [512, 512, 512, 512]
      activation: relu
      batch_norm: true
      dropout_p: 0.13
    inverse_model:
      num_layers: 2
      hidden_size: 64
      dropout_p: 0.17
      bidirectional: true
    discriminator_model:
      nb_frames: 5
      rnn:
        ff:
          activation: relu
          hidden_layers:
            - 128
            - 64
        lstm:
          bidirectional: true
          dropout_p: 0.25
          hidden_size: 64
          num_layers: 1
  synthesizer:
    name: ea587b76c95fecef01cfd16c7f5f289d-3
  dataset:
    names: [M0_10_mn]
    sound_type: cepstrum
    datasplits_size: [90, 10, 0] # train/validation/test in percentage
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
    audio_only: true
  babbling_dataset:
    name: pb2007
    sound_type: cepstrum
    art_type: art_params
    datasplits_size: [64, 16, 20]
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
  training:
    learning_rate: 0.0017
    discriminator_model_learning_rate: 0.002
    max_epochs: 500
    patience: 30
    jerk_loss_weight: 0
    discriminator_loss_weight: 100
    inverse_clip_value: 2

M0_60_mn:
  model:
    direct_model:
      hidden_layers: [512, 512, 512, 512]
      activation: relu
      batch_norm: true
      dropout_p: 0.13
    inverse_model:
      num_layers: 2
      hidden_size: 64
      dropout_p: 0.17
      bidirectional: true
    discriminator_model:
      nb_frames: 5
      rnn:
        ff:
          activation: relu
          hidden_layers:
            - 128
            - 64
        lstm:
          bidirectional: true
          dropout_p: 0.25
          hidden_size: 64
          num_layers: 1
  synthesizer:
    name: ea587b76c95fecef01cfd16c7f5f289d-3
  dataset:
    names: [M0_60_mn]
    sound_type: cepstrum
    datasplits_size: [90, 10, 0] # train/validation/test in percentage
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
    audio_only: true
  babbling_dataset:
    name: pb2007
    sound_type: cepstrum
    art_type: art_params
    datasplits_size: [ 64, 16, 20 ]
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
  training:
    learning_rate: 0.0017
    discriminator_model_learning_rate: 0.002
    max_epochs: 500
    patience: 15
    jerk_loss_weight: 0
    discriminator_loss_weight: 100
    inverse_clip_value: 2

M0_600_mn:
  model:
    direct_model:
      hidden_layers: [512, 512, 512, 512]
      activation: relu
      batch_norm: true
      dropout_p: 0.13
    inverse_model:
      num_layers: 2
      hidden_size: 64
      dropout_p: 0.17
      bidirectional: true
    discriminator_model:
      nb_frames: 5
      rnn:
        ff:
          activation: relu
          hidden_layers:
            - 128
            - 64
        lstm:
          bidirectional: true
          dropout_p: 0.25
          hidden_size: 64
          num_layers: 1
  synthesizer:
    name: ea587b76c95fecef01cfd16c7f5f289d-3
  dataset:
    names: [M0_600_mn]
    sound_type: cepstrum
    datasplits_size: [90, 10, 0] # train/validation/test in percentage
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
    audio_only: true
  babbling_dataset:
    name: pb2007
    sound_type: cepstrum
    art_type: art_params
    datasplits_size: [ 64, 16, 20 ]
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
  training:
    learning_rate: 0.0017
    discriminator_model_learning_rate: 0.002
    max_epochs: 500
    patience: 7
    jerk_loss_weight: 0
    discriminator_loss_weight: 100
    inverse_clip_value: 2

M0_6000_mn:
  model:
    direct_model:
      hidden_layers: [512, 512, 512, 512]
      activation: relu
      batch_norm: true
      dropout_p: 0.13
    inverse_model:
      num_layers: 2
      hidden_size: 64
      dropout_p: 0.17
      bidirectional: true
    discriminator_model:
      nb_frames: 5
      rnn:
        ff:
          activation: relu
          hidden_layers:
            - 128
            - 64
        lstm:
          bidirectional: true
          dropout_p: 0.25
          hidden_size: 64
          num_layers: 1
  synthesizer:
    name: ea587b76c95fecef01cfd16c7f5f289d-3
  dataset:
    names: [M0_6000_mn]
    sound_type: cepstrum
    datasplits_size: [90, 10, 0] # train/validation/test in percentage
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
    audio_only: true
  babbling_dataset:
    name: pb2007
    sound_type: cepstrum
    art_type: art_params
    datasplits_size: [ 64, 16, 20 ]
    datasplit_seed: 0
    batch_size: 8
    num_workers: 6
    shuffle_between_epochs: true
  training:
    learning_rate: 0.0017
    discriminator_model_learning_rate: 0.002
    max_epochs: 500
    patience: 3
    jerk_loss_weight: 0
    discriminator_loss_weight: 100
    inverse_clip_value: 2

